Milestone 5: Friendships v1
aristides1000/ror-social-scaffold pull request #3
Opened 2021-07-19 21:22 UTC by ad9311

Greetings 👋🏽 

In this PR we present the Milestone 5: Friendships v1 for the Social Media Website.
The following changes include:
- New friendship model
- Relations between friendship model and user model
- Methods for the user model to add handle frienship requests

2021-07-19 22:16 UTC, bellom requested changes
## Hi Team :clap: 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 

# Status: Changes Required! ♻️ 

1. Let's a button to invite users to friendship on the users list page and on the single-user page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))


2. Let's make sure posts timeline includes posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

3. Let's add unit and Integration tests! ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best**

2021-07-20 22:15 UTC, ad9311 commented
In this PR we present the following changes:
- User can send friendship requests from users#index and users#show
- Only the posts created by users you are friend with and yourself are shown
- If you have been sent a request you can:
  - Click on the button to the corresping requester in users#index that will redirect to their user's profile and then click to accept it.
  - If you click directly on their profile you will become friends.

2021-07-20 23:22 UTC, carlos-ssh requested changes
Hi @ad9311, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._ 👇🏼👇🏼👇🏼👇🏼

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-20 23:22 UTC, carlos-ssh commented on app/models/user.rb
> +  has_many :inverse_friendships, class_name: 'Friendship', foreign_key: 'friend_id'
**Kindly work on these changes:**
- User can reject a friendship request ( [screenshot ](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)).

**[OPTIONAL]**
**- Add your personal information and a license into your README file. Would be great to have fully detailed this file to improve your professionalism once the recruiters come to your repositories.**

2021-07-21 00:59 UTC, carlos-ssh approved these changes
Hi @ad9311 & @aristides1000, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-21 01:01 UTC, merged